---
lightcone_params:
  mturn: 
    num_samples: 2
    lightcone_shape: !!python/tuple [607, 128, 128]
    lightcone_dimensions: !!python/tuple [1214, 256, 256]
    astro_param_ranges:
        M_TURN: [8.5, 9.]
    p21c_kwargs:
      redshift: 6
      max_redshift: 10
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
