---
lightcone_params:

  bianco: 
    cache_name: "bianco"
    num_samples: 64
    lightcone_shape: !!python/tuple [297, 128, 128]
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    astro_param_distributions:
      HII_EFF_FACTOR: [30.0, 0.0] # param: [mean, sigma**2]
      R_BUBBLE_MAX: [15.0, 0.0] # Mpc
      ION_Tvir_MIN: [4.69, 0.0] # K
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
