---
lightcone_params:

  gillet: 
    cache_name: "gillet"
    num_samples: 64
    lightcone_shape: !!python/tuple [1007, 64, 64]
    lightcone_dimensions: !!python/tuple [3147, 200, 200]
    astro_param_ranges:
      HII_EFF_FACTOR: [10, 250] # param: [min, max]
      ION_Tvir_MIN: [4, 6]
      L_X: [38, 42]
      NU_X_THRESH: [100, 1500]
    p21c_kwargs:
      redshift: 6
      max_redshift: 30
      user_params: {HII_DIM: 64, BOX_LEN: 200, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
