---
lightcone_params:

  default: 
    cache_name: "mturn-87"
    num_samples: 64
    lightcone_shape: !!python/tuple [508, 64, 64]
    lightcone_dimensions: !!python/tuple [2032, 256, 256]
    p21c_kwargs:
      redshift: 6
      max_redshift: 15
      user_params: {HII_DIM: 64, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
      lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
      global_quantities: !!python/tuple ["brightness_temp", "density"]
