---
lightcone_params:

  cubes: 
    cache_name: "z6-13"
    num_samples: 1
    lightcone_shape: !!python/tuple [594, 128, 128]
    lightcone_dimensions: !!python/tuple [980, 256, 256]
    p21c_kwargs:
      redshift: 6
      max_redshift: 10
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
