---
lightcone_params:

  bianco: 
    cache_name: "bianco_double"
    num_samples: 64
    lightcone_shape: !!python/tuple [297, 128, 128]
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    astro_param_distributions:
      HII_EFF_FACTOR: [52.5, 20.0] # param: [mean, 2*sigma]
      R_BUBBLE_MAX: [12.5, 10.0] # Mpc
      ION_Tvir_MIN: [4.65, 1.0] # K
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
