---
lightcone_params:

  default: 
    cache_name: "mturn-87"
    num_samples: 64
    lightcone_shape: !!python/tuple [596, 64, 64]
    lightcone_dimensions: !!python/tuple [2384, 256, 256]
    astro_param_distributions:
      HII_EFF_FACTOR: [52.5, 20.0] # param: [mean, sigma]
      R_BUBBLE_MAX: [12.5, 5.0] # Mpc
      ION_Tvir_MIN: [4.65, 0.5] # K
    p21c_kwargs:
      redshift: 5
      max_redshift: 14
      user_params: {HII_DIM: 64, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
