---
lightcone_params:

  z6-13: 
    cache_name: "z6-13"
    num_samples: 16
    lightcone_shape: !!python/tuple [710, 128, 128]
    lightcone_dimensions: !!python/tuple [2840, 256, 256]
    astro_param_ranges:
      ION_Tvir_MIN: [4, 6]
      R_BUBBLE_MAX: [5, 15]
      L_X: [38, 42]
      NU_X_THRESH: [100, 1500]
      M_TURN: [8.5, 9.0]
    p21c_kwargs:
      redshift: 5
      max_redshift: 18
      flag_options: {'USE_MASS_DEPENDENT_ZETA': True}
      user_params: {HII_DIM: 128, BOX_LEN: 512, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
