---
desc: "Testing wide redshift range. M_TURN fixed at 8.7, all other values are default"
initial_conditions1: 
  num_samples: 4
  min_redshift: 6
  max_redshift: 13
  lightcone_quantities: ["brightness_temp", "density"]
  global_quantities: ["brightness_temp", "density"]
  user_params: {HII_DIM: 128, BOX_LEN: 512, N_THREADS: 5, USE_INTERPOLATION_TABLES: True} #HII_DIM = num_pixels per side, BOX_LEN = Mpc per side

