---
lightcone_params:

  m_turn_8.5: 
    cache_name: "mturn-85"
    lightcone_shape: !!python/tuple [297, 128, 128]
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    num_samples: 1
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      flag_options: {'USE_MASS_DEPENDENT_ZETA': True}
      astro_params: {'M_TURN': 8.5}
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
      lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
      global_quantities: !!python/tuple ["brightness_temp", "density"]
  
  m_turn_8.6: 
    cache_name: "mturn-86"
    lightcone_shape: !!python/tuple [297, 128, 128]
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    num_samples: 1
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      flag_options: {'USE_MASS_DEPENDENT_ZETA': True}
      astro_params: {'M_TURN': 8.6}
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
      lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
      global_quantities: !!python/tuple ["brightness_temp", "density"]
  
  m_turn_8.7: 
    cache_name: "mturn-87"
    num_samples: 1
    lightcone_shape: !!python/tuple [297, 128, 128]
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      flag_options: {'USE_MASS_DEPENDENT_ZETA': True}
      astro_params: {'M_TURN': 8.7}
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
      lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
      global_quantities: !!python/tuple ["brightness_temp", "density"]
  
  m_turn_8.8: 
    cache_name: "mturn-88"
    num_samples: 1
    lightcone_shape: !!python/tuple [297, 128, 128] 
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      flag_options: {'USE_MASS_DEPENDENT_ZETA': True}
      astro_params: {'M_TURN': 8.8}
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
      lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
      global_quantities: !!python/tuple ["brightness_temp", "density"]
  
  m_turn_8.9: 
    cache_name: "mturn-89"
    num_samples: 1
    lightcone_shape: !!python/tuple [297, 128, 128]
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      flag_options: {'USE_MASS_DEPENDENT_ZETA': True}
      astro_params: {'M_TURN': 8.9}
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
      lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
      global_quantities: !!python/tuple ["brightness_temp", "density"]
  
