---
lightcone_params:

  default: 
    cache_name: "default"
    num_samples: 64
    lightcone_shape: !!python/tuple [1007, 64, 64]
    lightcone_dimensions: !!python/tuple [3147, 200, 200]
    p21c_kwargs:
      redshift: 6
      max_redshift: 30
      user_params: {HII_DIM: 64, BOX_LEN: 200, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
