---
lightcone_params:

  default: 
    cache_name: "mturn-87"
    num_samples: 64
    lightcone_shape: !!python/tuple [297, 128, 128]
    lightcone_dimensions: !!python/tuple [594, 256, 256]
    p21c_kwargs:
      redshift: 7
      max_redshift: 9
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
      lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
      global_quantities: !!python/tuple ["brightness_temp", "density"]
