#
#  Config file for Gillet et al (2019) astroparameters.
#

---
lightcone_params:

  new_sweep_gillet: 
    num_samples: 64
    lightcone_shape: !!python/tuple [607, 128, 128]
    lightcone_dimensions: !!python/tuple [1214, 256, 256]
    astro_param_ranges: # NO HII_EFF to keep EoR in same range
      ION_Tvir_MIN: [4, 6]
      L_X: [38, 42]
      NU_X_THRESH: [100, 1500]
    p21c_kwargs:
      redshift: 6
      max_redshift: 10
      user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
