---
############################################################################
#  final_* variables contain information about lightcones post-processing  #
############################################################################
num_lightcones: 64
final_starting_redshift: 7
final_lightcone_shape: !!python/tuple [256, 128, 128]
final_lightcone_dimensions: !!python/tuple [512, 256, 256]
p21c_run_lightcone_kwargs:
  redshift: 6
  max_redshift: 10
  user_params: {HII_DIM: 128, BOX_LEN: 256, N_THREADS: 5, USE_INTERPOLATION_TABLES: True}
  lightcone_quantities: !!python/tuple ["brightness_temp", "density"]
  global_quantities: !!python/tuple ["brightness_temp", "density"]
original_lightcone_shape: !!python/tuple [607, 128, 128]
original_lightcone_dimensions: !!python/tuple [1214, 256, 256]
